CREATE SEQUENCE "USER_ID_SEQ" START WITH 1;
CREATE SEQUENCE "USER_USER_NUM_SEQ" START WITH 1;
CREATE TABLE "USER" (
    "ID" NUMBER NOT NULL DEFAULT "USER_ID_SEQ".nextval,
    "USERNAME" VARCHAR2(50) NOT NULL,
    "NAME" VARCHAR2(50) NOT NULL,
    "BIRTHDAY" DATE,
    "USER_NUM" NUMBER NOT NULL DEFAULT "USER_USER_NUM_SEQ".nextval,
    "ACTIVE" NUMBER(1, 0) NOT NULL,
    "COUNTRY_ID" NUMBER NOT NULL,
    "ALTERNATIVE_COUNTRY_ID" NUMBER,
    CONSTRAINT "USER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "USER_USERNAME_UNIQUE" UNIQUE ("USERNAME")
);

CREATE SEQUENCE "COUNTRY_THE_COUNTRY_ID_SEQ" START WITH 1;
CREATE TABLE "COUNTRY" (
    "THE_COUNTRY_ID" NUMBER NOT NULL DEFAULT "COUNTRY_THE_COUNTRY_ID_SEQ".nextval,
    "CODE" VARCHAR2(5) NOT NULL,
    "NAME" VARCHAR2(100) NOT NULL,
    CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("THE_COUNTRY_ID")
);

CREATE SEQUENCE "PERMISSION_ID_SEQ" START WITH 1;
CREATE TABLE "PERMISSION" (
    "ID" NUMBER NOT NULL DEFAULT "PERMISSION_ID_SEQ".nextval,
    "CODE" VARCHAR2(30) NOT NULL,
    "DESCRIPTION" VARCHAR2(200) NOT NULL,
    CONSTRAINT "PERMISSION_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "TREE_ID_SEQ" START WITH 1;
CREATE TABLE "TREE" (
    "ID" NUMBER NOT NULL DEFAULT "TREE_ID_SEQ".nextval,
    "HEAD_NODE_ID" NUMBER NOT NULL,
    CONSTRAINT "TREE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "TREE_HEAD_NODE_ID_UNIQUE" UNIQUE ("HEAD_NODE_ID")
);

CREATE SEQUENCE "TREE_NODE_ID_SEQ" START WITH 1;
CREATE TABLE "TREE_NODE" (
    "ID" NUMBER NOT NULL DEFAULT "TREE_NODE_ID_SEQ".nextval,
    "VALUE" NUMBER NOT NULL,
    "PARENT_ID" NUMBER,
    CONSTRAINT "TREE_NODE_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "USER_PERMISSION_ID_SEQ" START WITH 1;
CREATE TABLE "USER_PERMISSION" (
    "ID" NUMBER NOT NULL DEFAULT "USER_PERMISSION_ID_SEQ".nextval,
    "USER_ID" NUMBER NOT NULL,
    "PERMISSION_ID" NUMBER NOT NULL,
    CONSTRAINT "USER_PERMISSION_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "FOLLOWS_ID_SEQ" START WITH 1;
CREATE TABLE "FOLLOWS" (
    "ID" NUMBER NOT NULL DEFAULT "FOLLOWS_ID_SEQ".nextval,
    "FOLLOWER_ID" NUMBER NOT NULL,
    "FOLLOW_ID" NUMBER NOT NULL,
    CONSTRAINT "FOLLOWS_PK" PRIMARY KEY ("ID")
);

ALTER TABLE "USER" ADD CONSTRAINT "USER_COUNTRY_ID_FK" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRY" ("THE_COUNTRY_ID");
ALTER TABLE "USER" ADD CONSTRAINT "USER_ALTERNATIVE_COUNTRY_ID_FK" FOREIGN KEY ("ALTERNATIVE_COUNTRY_ID") REFERENCES "COUNTRY" ("THE_COUNTRY_ID");

ALTER TABLE "TREE" ADD CONSTRAINT "TREE_HEAD_NODE_ID_FK" FOREIGN KEY ("HEAD_NODE_ID") REFERENCES "TREE_NODE" ("ID");

ALTER TABLE "TREE_NODE" ADD CONSTRAINT "TREE_NODE_PARENT_ID_FK" FOREIGN KEY ("PARENT_ID") REFERENCES "TREE_NODE" ("ID");

ALTER TABLE "USER_PERMISSION" ADD CONSTRAINT "USER_PERMISSION_USER_ID_FK" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "USER_PERMISSION" ADD CONSTRAINT "USER_PERMISSION_PERMISSION_ID_FK" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION" ("ID");

ALTER TABLE "FOLLOWS" ADD CONSTRAINT "FOLLOWS_FOLLOWER_ID_FK" FOREIGN KEY ("FOLLOWER_ID") REFERENCES "USER" ("ID");
ALTER TABLE "FOLLOWS" ADD CONSTRAINT "FOLLOWS_FOLLOW_ID_FK" FOREIGN KEY ("FOLLOW_ID") REFERENCES "USER" ("ID");
